server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zjc?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true #允许我们自己覆盖spring放入到IOC容器的对象
  session:
    store-type: none
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9002/oauth/token
      user-authorization-uri: http://localhost:9002/oauth/authorize
      client-id: zjc
      client-secret: 123
#      client-authentication-scheme: form
      # 定义false表示默认跳转路径（/login）不生效
      use-current-uri: false
      #使用自定义跳转路径  前提是use-current-uri必须为false,与数据库中配置的跳转路径一致
#      pre-established-redirect-uri: http://localhost:8081/
      grant-type: authorization_code
    resource:
      userInfoUri: http://localhost:8035/user
      preferTokenInfo: false #true表示使用token，false表示使用user